apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-adminer
  labels:
    app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aminier
  template:
    metadata:
      labels:
        app: aminier
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080